#!/bin/bash

x=`pwd`
gradleExec=`pwd`/gradlew

while [[ ! -e "$gradleExec" && $x != "/" ]]; do
    if [ -x "$x/gradlew" ]; then
        gradleExec="$x/gradlew"
        break
    fi
    x=`dirname "$x"`
done

if [ ! -x "$gradleExec" ]; then
    gradleExec=$GRADLE_HOME/bin/gradle
fi

$gradleExec $@
